In [3]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [4]:
#https://towardsdatascience.com/upgrade-your-memory-on-google-colab-for-free-1b8b18e8791d

In [5]:
gpu_info = !nvidia-smi
gpu_info = '\n'.join(gpu_info)
if gpu_info.find('failed') >= 0:
  print('Not connected to a GPU')
else:
  print(gpu_info)

Sat Sep  2 05:58:50 2023       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 525.105.17   Driver Version: 525.105.17   CUDA Version: 12.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   40C    P8     9W /  70W |      0MiB / 15360MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

In [6]:
!pip3 install bert
!pip3 install torch==1.2.0 torchvision==0.4.0 -f
!pip install -U sentence-transformers


Usage:   
  pip3 install [options] <requirement specifier> [package-index-options] ...
  pip3 install [options] -r <requirements file> [package-index-options] ...
  pip3 install [options] [-e] <vcs project url> ...
  pip3 install [options] [-e] <local project path> ...
  pip3 install [options] <archive url/path> ...

-f option requires 1 argument


In [7]:
import pandas as pd
import pickle
import numpy as np
data=pd.read_csv('/content/drive/MyDrive/data_colab/RecipeNLG_dataset.csv')
data['NER']
data.head()

FileNotFoundError: ignored

In [8]:
sentences = data['ingredients']+' '+data['title']+' '+data['directions']+' '+data['source']+' '+data['NER']
from sentence_transformers import SentenceTransformer

NameError: ignored

In [1]:
from sklearn.metrics.pairwise import cosine_similarity
model = SentenceTransformer('bert-base-nli-mean-tokens')
sentences=sentences[:10]
#model =SentenceTransformer(model_name)
#sentence_vecs=pickle.load(open("sentence_vecs.pkl","rb"))
sentence_vecs=model.encode(sentences)
sentence_vecs.shape
sentence_vecs
#768 hidden stage size
pickle.dump(sentence_vecs,open("/content/sentence_vecs.pkl","wb"))

#sentence_vecs=pd.read_pickle("/content/drive/MyDrive/data_colab/sentence_vecs.pkl")

NameError: ignored

In [ ]:
pickle.dump(sentence_vecs,open("/content/drive/MyDrive/data_colab/sentence_vecs.pkl","wb"))

In [2]:
import pickle
import pandas as pd
sentence_vecs=pd.read_pickle("/content/drive/MyDrive/Colab Notebooks/data/Food_Recommendation/sentence_vecs.pkl")
from sklearn.metrics.pairwise import cosine_similarity


x=cosine_similarity(
    [sentence_vecs[0]],
    sentence_vecs[1:]
)
x

array([[0.6995939 , 0.8278533 , 0.7502638 , ..., 0.82849574, 0.73628926,
        0.83617485]], dtype=float32)

In [ ]:
cs=cosine_similarity(sentence_vecs)
recipe_ids=[0,1,2,3]

In [ ]:


def return_similar_items(similarities,recipe_ids,topk):
    return np.array(list(sorted(list(zip(recipe_ids,similarities)),reverse=True,key= lambda x:x[1])),
                    dtype=np.dtype({'names':('recipe_ids','similarity'),'formats':('i8','f8')}))

similarities_sorted=np.apply_along_axis(return_similar_items,topk=10,recipe_ids=recipe_ids,arr=cs,axis=1)
similarities_sorted

In [ ]:
top_k=10
arr_1=[]
for i in similarities_sorted.tolist():
    arr1=[]
    for ind,v in enumerate(i):
        #if v[0] in current_ids:
        arr1.append(v)
    arr_1.append(arr1)

In [ ]:
arr_1

In [ ]:
arr=list(map(lambda x:x[:top_k],arr_1))
top_k=min(top_k,len(arr[0]))
similarities_sorted_df=pd.DataFrame(arr,columns=range(len(arr[0])))
sim_df=similarities_sorted_df.applymap(lambda x:x[1])
sim_df=sim_df.rename(columns = {i:i+1 for i in range(top_k)})
sim_df.columns=sim_df.columns.astype(str)

In [ ]:
sim_df[1].sort_values(ascending=False)[1:10]
index=sim_df[1].sort_values(ascending=False)[1:10].index

In [ ]:
1

In [ ]:
# delte the below

In [ ]:
from sentence_transformers import SentenceTransformer, util
model = SentenceTransformer('all-MiniLM-L6-v2')

sentences = ['A man is eating food.',
          'A man is eating a piece of bread.',
          'The girl is carrying a baby.',
          'A man is riding a horse.',
          'A woman is playing violin.',
          'Two men pushed carts through the woods.',
          'A man is riding a white horse on an enclosed ground.',
          'A monkey is playing drums.',
          'Someone in a gorilla costume is playing a set of drums.'
          ]

#Encode all sentences
embeddings = model.encode(sentences)

#Compute cosine similarity between all pairs
cos_sim = util.cos_sim(embeddings, embeddings)

#Add all pairs to a list with their cosine similarity score
all_sentence_combinations = []
for i in range(len(cos_sim)-1):
    for j in range(i+1, len(cos_sim)):
        all_sentence_combinations.append([cos_sim[i][j], i, j])

#Sort list by the highest cosine similarity score
all_sentence_combinations = sorted(all_sentence_combinations, key=lambda x: x[0], reverse=True)

print("Top-5 most similar pairs:")
for score, i, j in all_sentence_combinations[0:5]:
    print("{} \t {} \t {:.4f}".format(sentences[i], sentences[j], cos_sim[i][j]))


ModuleNotFoundError: ignored

In [ ]:
#https://towardsdatascience.com/bert-for-measuring-text-similarity-eec91c6bf9e1
sentences = [
    "Three years later, the coffin was still full of Jello.",
    "The fish dreamed of escaping the fishbowl and into the toilet where he saw his friend go.",
    "The person box was packed with jelly many dozens of months later.",
    "He found a leprechaun in his walnut shell."
]
!pip3 install bert

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [ ]:
sentence_vecs

array([[ 0.0744616 ,  0.86369675,  0.17946415, ...,  0.77343965,
         1.7247485 , -0.18027496],
       [-0.37146333,  0.97290134,  1.0839939 , ..., -0.25521287,
        -0.2759377 ,  0.03575849],
       [-0.5029822 ,  0.7949858 , -0.12402503, ...,  0.14406323,
         0.9703752 , -0.17911568],
       [-0.21311912,  1.0174935 , -0.8832757 , ...,  0.73710394,
         0.19469142, -0.30111265]], dtype=float32)

In [ ]:

from sentence_transformers import SentenceTransformer

model = SentenceTransformer('bert-base-nli-mean-tokens')

#model =SentenceTransformer(model_name)
sentence_vecs=model.encode(sentences)
sentence_vecs.shape
sentence_vecs
#768 hidden stage size

from sklearn.metrics.pairwise import cosine_similarity

cosine_similarity(
    [sentence_vecs[0]],
    sentence_vecs[1:]

)

array([[0.3308891 , 0.72192585, 0.55483633]], dtype=float32)

In [ ]:

from sentence_transformers import SentenceTransformer

model = SentenceTransformer('bert-base-nli-mean-tokens')

#model =SentenceTransformer(model_name)
sentence_vecs=model.encode(sentences)
sentence_vecs.shape
sentence_vecs
#768 hidden stage size

from sklearn.metrics.pairwise import cosine_similarity

cosine_similarity(
    [sentence_vecs[0]],
    sentence_vecs[1:]

)

array([[0.3308891 , 0.72192585, 0.55483633]], dtype=float32)

(4, 768)

In [ ]:
from sentence_transformers import SentenceTransformer
model = SentenceTransformer('paraphrase-MiniLM-L6-v2')

#Sentences we want to encode. Example:
sentence = ['This framework generates embeddings for each input sentence']


#Sentences are encoded by calling model.encode()
embedding = model.encode(sentence)



In [ ]:

####### Same code with transformers and torch
model_name='sentence-transformers/bert-base-nli-mean-tockens'

from transformers import AutoTokenizer, AutoModel
import torch
tokenizer=AutoTokenizer.from_pretrained(model_name)
model=AutoModel.from_pretrained(model_name)

tokens={'input_ids':[],'attention_mask':[]}
for sentence in sentences:
        new_tockens=tokenizer.encode_plus(sentence,max_len=128,truncation=True, padding='max_length',return_tensors='pt')
        new_tockens['input_ids'].append(new_tockens['input_ids'])
        tockens['attention_mask'].append(new_tokens['attention_mask'][0])


outputs=model(**tockens)

OSError: ignored

In [ ]:




####### Same code with transformers and torch
model_name='sentence-transformers/bert-base-nli-mean-tockens'

from transformers import AutoTokenizer, AutoModel
import torch
tokenizer=AutoTokenizer.from_pretrained(model_name)
model=AutoModel.from_pretrained(model_name)

tokens={'input_ids':[],'attention_mask':[]}
for sentence in sentences:
        new_tockens=tokenizer.encode_plus(sentence,max_len=128,truncation=True, padding='max_length',return_tensors='pt')
        new_tockens['input_ids'].append(new_tockens['input_ids'])
        tockens['attention_mask'].append(new_tokens['attention_mask'][0])


outputs=model(**tockens)

outputs.keys()

embeddings=outpurs.last_hidden_state
embeddings.shape



attention_mask = tokens['attention_mask']
attention_mask.shape


mask = attention_mask.unsqueeze(-1).expand(embeddings.size()).float()
mask.shape

mask

masked_embeddings = embeddings * mask
masked_embeddings.shape

masked_embeddings

summed = torch.sum(masked_embeddings, 1)
summed.shape

summed_mask = torch.clamp(mask.sum(1), min=1e-9)
summed_mask.shape

summed_mask

mean_pooled = summed / summed_mask

mean_pooled


Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
  Preparing metadata (setup.py) ... done
  Preparing metadata (setup.py) ... done
  Created wheel for bert: filename=bert-2.2.0-py3-none-any.whl size=3764 sha256=22acb68e77b2496bda772cbf0e739a0bd0cca4b4359c149c5acffb56374832cf
  Stored in directory: /root/.cache/pip/wheels/65/11/40/6439aef2635f7f0137a79c4defb4c4e65dd051ec0198429e3b
  Created wheel for erlastic: filename=erlastic-2.0.0-py3-none-any.whl size=6795 sha256=0886c9a8e268109e35efb1a62ca4d1198f2167d8ede2ff714703649ea27c63d3
  Stored in directory: /root/.cache/pip/wheels/ee/c9/a6/41a81618e939b746a3151700565d191bca832b6c345ea9b87a
Successfully built bert erlastic

Usage:   
  pip3 install [options] <requirement specifier> [package-index-options] ...
  pip3 install [options] -r <requirements file> [package-index-options] ...
  pip3 install [options] [-e] <vcs project url> ...
  pip3 install [options] [-e] <local project path> ...
  p

OSError: ignored

In [ ]:
sentences = [
    "Three years later, the coffin was still full of Jello.",
    "The fish dreamed of escaping the fishbowl and into the toilet where he saw his friend go.",
    "The person box was packed with jelly many dozens of months later.",
    "He found a leprechaun in his walnut shell."
]

In [ ]:
from sentence_transformers import SentenceTransformer

model = SentenceTransformer('bert-base-nli-mean-tokens')

In [ ]:
sentence_embeddings = model.encode(sentences)


In [ ]:
sentence_embeddings.shape


(4, 768)

In [ ]:
from sklearn.metrics.pairwise import cosine_similarity
cosine_similarity(
    [sentence_embeddings[0]],
    sentence_embeddings[1:]
)

array([[0.3308891 , 0.72192585, 0.55483633]], dtype=float32)